import { type VercelConfig, routes } from '@vercel/config/v1';

// Earlier rules win when more than one matches the same response header, so the
// most specific / most aggressive Cache-Control rules are listed first.
//
// Not covered here on purpose:
//   - The server-rendered HTML document (/) is cached and regenerated by
//     Incremental Static Regeneration, configured via `isr` on the Vercel adapter
//     in astro.config.ts — that owns document caching, so there's no rule for it.
//   - Vercel Image Optimization responses (`/_vercel/image?...`) are cached by
//     Vercel's optimizer itself, driven by `imagesConfig.minimumCacheTTL` in
//     astro.config.ts (one year); their headers can't be overridden here.
export const config: VercelConfig = {
  headers: [
    // Astro's build output — JS, CSS, the self-hosted web fonts, and the images
    // Astro fingerprints at build time — is emitted under /_astro/ with
    // content-hashed filenames. New content means a new URL, so these can be
    // cached forever and never revalidated.
    routes.cacheControl('/_astro/(.*)', {
      public: true,
      maxAge: '1y',
      immutable: true,
    }),

    // Static files served straight out of /public (favicons & SVG icons, the
    // PNG art and sprites, sponsor logos, the click sound, fonts). These have
    // stable, un-hashed URLs and can be swapped without changing the path, so
    // the browser holds them for a day and the CDN for a week while serving the
    // old copy and revalidating in the background after a swap.
    routes.cacheControl(
      '/(.*)\\.(svg|png|jpe?g|gif|webp|avif|ico|woff2?|ttf|otf|wav|mp3|webmanifest)',
      {
        public: true,
        maxAge: '1d',
        sMaxAge: '1w',
        staleWhileRevalidate: '1d',
      }
    ),
  ],
};
